### ISSUE TITLE
Adding more than one file!! Important!

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#16]
When you try to add a file, there is only the possibility to add one. Adding more than 1 file.

**Comment by AshanthaLahiru** [comment]
Working on that!

**Comment by alexsicart** [comment]
@AshanthaLahiru Thanks!! Waiting for your pull request :)

**Comment by moranlemusj** [comment]
pull request incoming

**Comment by alexsicart** [comment]
Thanks @moranlemusj
