### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#25]
## Expected Behavior
It should have a better design as https://wetransfer.com/ to make it easier for costumers.

## Actual Behavior
The web is not beautiful yet. Everything works correctly.

**Comment by sunnyday90210** [comment]
I love this project I will start working on the ui

**Comment by 0x48piraj** [comment]
I too want to work on this ! :heart_eyes:

**Comment by 0x48piraj** [comment]
Is there any source of this site ?
Or, I have to build it from scratch ? :open_mouth:

**Comment by sunnyday90210** [comment]
@0x48piraj go to https://github.com/alexsicart/Decentralized-Cloud and fork

**Comment by alexsicart** [comment]
Thanks!! :) @sunnyday90210

**Comment by 0x48piraj** [comment]
Where are the `.html` files ?

**Comment by sunnyday90210** [comment]
@0x48piraj this is built in angular the components are in the src folder

**Comment by sunnyday90210** [comment]
@alexsicart here is just a test in html I had alot of problems with the packages now working everytime I fixed one another one was broken so I could not get angular running with this app. I will have to try tomorrow this is just a first test let me know if this is the idea your looking for https://sunnyday90210.github.io/decentralized-cloud-test/

**Comment by alexsicart** [comment]
I love the design of this test!! This app doesn't work with ng serve/ng build (common angular). Works with npm start/npm build.

**Comment by sunnyday90210** [comment]
@alexsicart this is my final test if you like the design I will try and integrate into angular https://sunnyday90210.github.io/decentralized-cloud-final-test/

**Comment by alexsicart** [comment]
@sunnyday90210 I love the buttons (the top one, to add files), and the title. If you can make a pull request in angular, changing the title for the one you've done and the buttons will be greaaat!!

**Comment by sunnyday90210** [comment]
@alexsicart I will make those changes tonight and then work on mobile friendly.

**Comment by alexsicart** [comment]
@sunnyday90210 cool!!

**Comment by alexsicart** [comment]
@sunnyday90210 what do you think of this design? https://github.com/alexsicart/Decentralized-Cloud/tree/new-ui Inspire 100% on we transfer, very minimalistic.

**Comment by sunnyday90210** [comment]
@alexsicart I really like the new design, I think it looks great. here is something you can take a look at https://codepen.io/sunnyday90210/full/EbNrON/

**Comment by alexsicart** [comment]
@sunnyday90210 I like! A good way to explain what the project is about, the tech and contributors. without removing the simplicity of WeTransfer.

**Comment by alexsicart** [comment]
Also I like the idea to change image --> video from https://videos.pexels.com/

**Comment by sunnyday90210** [comment]
@alexsicart I agree it will make it a little different from the rest of the file sites. Just let me what you need to be done.

**Comment by alexsicart** [comment]
@sunnyday90210 it would be nice to have video instead of image. And the about, ipfs... below the page (like https://codepen.io/sunnyday90210/full/EbNrON/), when scrolling down. Keeping full screen for the video and the transfer container.

**Comment by sunnyday90210** [comment]
@alexsicart so a full-screen video with parallax scrolling for the about etc? Or you want the about and ipfs pages to float over the video background on scroll?  If you have any example site please show me.

**Comment by sunnyday90210** [comment]
@alexsicart https://www.spaceneedle.com/home/
http://www.alquimiawrg.com/#/home
http://www.sbs.com.au/theboat/
http://www.the-artery.com/

**Comment by alexsicart** [comment]
@sunnyday90210 yeah! Like this webpages. http://www.the-artery.com/

**Comment by sunnyday90210** [comment]
@alexsicart I will start working on it this week and see what I can come up with.

**Comment by alexsicart** [comment]
@sunnyday90210 cool!
