### ISSUE TITLE
Public Writable Gateway node

### ISSUE THREAD

**Issue by koalalorenzo** [alexsicart/Decentralized-Cloud#26]
I am considering to solve the main problem caused by the immaturity of js-ipfs by offering hosting and one IPFS public writable node.

How does it sound? Will this help?

**Comment by alexsicart** [comment]
Oh yess! It sounds amazing!! It'll help!! :) @koalalorenzo

**Comment by alexsicart** [comment]
Keep me in the loop!

**Comment by alexsicart** [comment]
Yes safari doesn't support crypto-lib :(

**Comment by koalalorenzo** [comment]
For now, but is `js-ipfs-api` working on safari, right? We could hook this there!

**Comment by alexsicart** [comment]
But the api only works if there is a node running on your computer, not as js-ipfs, can start a node on the browser

**Comment by koalalorenzo** [comment]
I am pretty sure it will work if we point the base url to an external instances (meaning: we don’t use localhost but a domain forth API calls). It was working when I am using my raspberrypi with js-ipfs-api on Lumpy!

The approach is the same as the one used by myetherwallet or MetaMask with Ethereum nodes

How much effort would it be to switch from js-ipfs to js-ipfs-api?

**Comment by cbluth** [comment]
I have public writable gateways at https://ipfs.work, https://ipfs.works, and https://ipfs.macholibre.org
