### ISSUE TITLE
Issue with the files uploading

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#3]
I can't upload more than 50mb using ipfs

**Comment by diasdavid** [comment]
which issue? Could you describe more?

**Comment by diasdavid** [comment]
try https://github.com/alexsicart/Decentralized-Cloud/issues/4 and let me know if this is still a issue

**Comment by alexsicart** [comment]
@diasdavid the issue was with the maximum size of the file, with more than 50mb the browser crash.
Thanks! still issue, but so much faster with the update!

**Comment by diasdavid** [comment]
@alexsicart Node.js Streams shim consume a lot of memory, see https://github.com/ipfs/js-ipfs/issues/952#issuecomment-326990430, uploading 300MB and more! :)

**Comment by alexsicart** [comment]
Wooow! thanks! :) I''ll take a look & implement! I'll let you know!
