### ISSUE TITLE
New name for https://decentralized.cloud/

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#39]

**Comment by mathiasrw** [comment]
www.transfer.cloud (only $18,999)

**Comment by mathiasrw** [comment]
www.file.bingo

**Comment by mathiasrw** [comment]
www.file.garden

**Comment by mathiasrw** [comment]
www.transfer.surf

**Comment by mathiasrw** [comment]
www.sendfile.gratis

**Comment by sunnyday90210** [comment]
snapcloud.io
synccloud.io
rapidcloud.io

**Comment by mathiasrw** [comment]
Snapcloud.io ! 

(made a new comment with input from @sunnyday90210 so people can upvote with 👍  )

**Comment by alexsicart** [comment]
I love https://snapcloud.io/ @sunnyday90210 I bought, is online! thanks!!! Really amazing name.

**Comment by sunnyday90210** [comment]
@alexsicart that awesome It looks great.

**Comment by mathiasrw** [comment]
Guess the repo should be renamed too :)

**Comment by alexsicart** [comment]
@mathiasrw Before doing that, I'm trying to know what people think --> https://twitter.com/alexsicart/status/927684981899628546

**Comment by mathiasrw** [comment]
www.weceive.com is free! go go go...

**Comment by mathiasrw** [comment]
So what did you end up width @alexsicart ?
