### ISSUE TITLE
Update to ipfs 0.26 for perf and mem usage improvs!

### ISSUE THREAD

**Issue by diasdavid** [alexsicart/Decentralized-Cloud#4]
Hi @alexsicart! This is really cool!

One tip, if you update to js-ipfs 0.26 today, your users will see a lot of perf and mem usage improvements. API remained the same. See release notes here: https://github.com/ipfs/js-ipfs/issues/986

**Comment by diasdavid** [comment]
Another note, this https://github.com/alexsicart/Decentralized-Cloud/blob/gh-pages/src/app/ipfs.service.ts#L26-L45 can be simplified to:

```
const node = new IPFS({
  repo: 'ipfs-' + Math.random()
})

node.on('ready', () => console.log('Online status: ', this.node.isOnline() ? 'online' : 'offline'))
```

See more on https://github.com/ipfs/js-ipfs#create-a-ipfs-node-instance :)

**Comment by alexsicart** [comment]
Done! So much better! Thanks a lot! :)
