### ISSUE TITLE
The logo is not displaying

### ISSUE THREAD

**Issue by sunnyday90210** [alexsicart/Decentralized-Cloud#43]
![capture](https://user-images.githubusercontent.com/26734422/32413789-cd4f0222-c1cd-11e7-9155-6d4acf343044.PNG)

**Comment by sunnyday90210** [comment]
@alexsicart let me know if you need to fix something with the logo it renders fine for me on my dev server.

**Comment by alexsicart** [comment]
@sunnyday90210 Solved!! :)
