### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by PandawanFr** [alexsicart/Decentralized-Cloud#46]
Hey, it would be awesome if you could drag and drop a file to add it to the website. 

The best thing would be to do like Imgur where you can drop anywhere on the page. But you could just as well make it so that you have to drop it on the "Add your files" icon (if it's easier).

**Comment by alexsicart** [comment]
@PandawanFr Great idea!! Thanks!

**Comment by moranlemusj** [comment]
Working on this
