### ISSUE TITLE
ng build --prod doesn't work.

### ISSUE THREAD

**Issue by alexsicart** [alexsicart/Decentralized-Cloud#8]
@polbaladas ng build works but the flag that reduce the size of the project is not working in this project.

**Comment by alexsicart** [comment]
ERROR in vendor.6b2608bb27b10dd36fea.bundle.js from UglifyJs
Unexpected token: name (p) [vendor.6b2608bb27b10dd36fea.bundle.js:1143,6]

**Comment by EricAlcaide** [comment]
It is already solved, isn't it?
